import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { Theme, Container } from '@radix-ui/themes'

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>
        <Theme>
          <main>
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  )
}
